# Generated by Django 5.1.2 on 2025-09-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_total_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=200)),
                ('name', models.TextField()),
                ('price', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
