# Generated by Django 5.1.2 on 2025-09-02 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_items_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
