# Generated by Django 5.1.2 on 2025-09-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='merchant_id',
            field=models.UUIDField(default=2),
            preserve_default=False,
        ),
    ]
