# Generated by Django 5.1.2 on 2025-09-02 19:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_items_merchant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('main', models.CharField()),
                ('review', models.CharField()),
                ('caption', models.TextField()),
                ('verdict', models.BooleanField()),
            ],
        ),
    ]
