# Generated by Django 5.1.2 on 2025-09-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='merchant',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='user',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
    ]
