# Generated by Django 5.1.2 on 2025-09-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_refund_merchant_refund_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='verdict',
            field=models.CharField(),
        ),
    ]
