# Generated by Django 5.1.2 on 2025-09-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_refund_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
