# Generated by Django 5.1.2 on 2025-09-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='merchant',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='refund',
            name='user',
            field=models.CharField(),
        ),
    ]
