# Generated by Django 5.1.2 on 2025-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_refund_merchant_alter_refund_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='item_id',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
    ]
