# Generated by Django 5.1.2 on 2025-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_refund_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='item_id',
        ),
        migrations.AddField(
            model_name='refund',
            name='item_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
