# Generated by Django 5.1.2 on 2025-09-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_refund_item_id_refund_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='item_description',
        ),
        migrations.AddField(
            model_name='refund',
            name='item_id',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
    ]
