# Generated by Django 5.1.2 on 2025-09-05 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_refund_item_description_refund_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
